[package]
edition = "2021"
name = "v001-hello-world"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = {version = "^1.2", features = ["fltk-bundled"]}
