[package]
edition = "2021"
name = "v112-struct"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = {version = "2.4", features = ['derive']}
rand = "0.8"
