[package]
edition = "2021"
name = "v117-tokio"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.18.2", features = ["full"]}
regex = "1.6.0"
httpdate = "1.0.2"